security:
    # https://symfony.com/doc/current/security.html#registering-the-user-hashing-passwords
    password_hashers:
        App\Entity\User: 'auto'

    # https://symfony.com/doc/current/security.html#loading-the-user-the-user-provider
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            # Ensure dev tools and static assets are always allowed
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        # /api/users/create endpoint'iga POST orqali murojaat qilinganda - token so'ralmasin
#        user_create:
#            pattern: ^/api/users/create$
#            methods:
#                - post
#            security: false

        main:
            stateless: true
            provider: app_user_provider
            json_login:
                check_path: /api/login
                username_path: email
                password_path: password
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
            jwt: ~

    # Note: Only the *first* matching rule is applied
#    access_control:
#        - { path: ^/api/.+, roles: IS_AUTHENTICATED_FULLY }
#        - { path: ^/api, roles: PUBLIC_ACCESS }
    access_control:
        # login va register ochiq
        - { path: ^/api/login, roles: PUBLIC_ACCESS }
        - { path: ^/api/users/create, roles: PUBLIC_ACCESS }

        # swagger ochiq bo‘lishi mumkin
        - { path: ^/api/docs, roles: PUBLIC_ACCESS }

        # hamma API lar token bilan
#        - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }
